# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20170327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.Room'),
        ),
    ]
