# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20170408_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='player_four_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player_one_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player_three_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='player_two_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
